// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'1901f3c566c7c41e94ac93605244604a644ac7216af4d4636540865a662d21b0'>;
export type ExecutionHash =
  ExecutionHashBase<'c1e234d6290ecad6a04273617ab9734ea92e2728fa81e095fee92ac7137c9b25'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Entidad: {
      readonly idEntidad: CodecTypes['pg/int4@1']['output'];
      readonly ruc: Varchar<11> | null;
      readonly razonSocial: Varchar<200> | null;
      readonly nombreComercial: Varchar<200>;
      readonly tipoEntidad: 'PUBLICA' | 'PRIVADA' | 'RELIGIOSA' | 'OTROS';
      readonly telefono: Varchar<15> | null;
      readonly correoElectronico: Varchar<150> | null;
      readonly redesSociales: Varchar<250> | null;
      readonly direccion: Varchar<250> | null;
      readonly codigoUbigeo: Varchar<6> | null;
      readonly esActivo: CodecTypes['pg/bool@1']['output'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechaModificacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly PersonaNatural: {
      readonly idPersonaNatural: CodecTypes['pg/int4@1']['output'];
      readonly nombres: Varchar<100>;
      readonly apellidoPaterno: Varchar<100>;
      readonly apellidoMaterno: Varchar<100> | null;
      readonly telefono: Varchar<15> | null;
      readonly correoElectronico: Varchar<150>;
      readonly dni: Varchar<8> | null;
      readonly direccion: Varchar<250> | null;
      readonly codigoUbigeo: Varchar<6> | null;
      readonly esActivo: CodecTypes['pg/bool@1']['output'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fechaModificacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Proyecto: { readonly idProyecto: CodecTypes['pg/uuid@1']['output'] };
    readonly Ubigeo: {
      readonly idUbigeo: Varchar<6>;
      readonly departamento: Varchar<100>;
      readonly provincia: Varchar<100>;
      readonly distrito: Varchar<100>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Entidad: {
      readonly idEntidad: CodecTypes['pg/int4@1']['input'];
      readonly ruc: CodecTypes['sql/varchar@1']['input'] | null;
      readonly razonSocial: CodecTypes['sql/varchar@1']['input'] | null;
      readonly nombreComercial: CodecTypes['sql/varchar@1']['input'];
      readonly tipoEntidad: 'PUBLICA' | 'PRIVADA' | 'RELIGIOSA' | 'OTROS';
      readonly telefono: CodecTypes['sql/varchar@1']['input'] | null;
      readonly correoElectronico: CodecTypes['sql/varchar@1']['input'] | null;
      readonly redesSociales: CodecTypes['sql/varchar@1']['input'] | null;
      readonly direccion: CodecTypes['sql/varchar@1']['input'] | null;
      readonly codigoUbigeo: CodecTypes['sql/varchar@1']['input'] | null;
      readonly esActivo: CodecTypes['pg/bool@1']['input'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechaModificacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly PersonaNatural: {
      readonly idPersonaNatural: CodecTypes['pg/int4@1']['input'];
      readonly nombres: CodecTypes['sql/varchar@1']['input'];
      readonly apellidoPaterno: CodecTypes['sql/varchar@1']['input'];
      readonly apellidoMaterno: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telefono: CodecTypes['sql/varchar@1']['input'] | null;
      readonly correoElectronico: CodecTypes['sql/varchar@1']['input'];
      readonly dni: CodecTypes['sql/varchar@1']['input'] | null;
      readonly direccion: CodecTypes['sql/varchar@1']['input'] | null;
      readonly codigoUbigeo: CodecTypes['sql/varchar@1']['input'] | null;
      readonly esActivo: CodecTypes['pg/bool@1']['input'];
      readonly fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fechaModificacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Proyecto: { readonly idProyecto: CodecTypes['pg/uuid@1']['input'] };
    readonly Ubigeo: {
      readonly idUbigeo: CodecTypes['sql/varchar@1']['input'];
      readonly departamento: CodecTypes['sql/varchar@1']['input'];
      readonly provincia: CodecTypes['sql/varchar@1']['input'];
      readonly distrito: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly gp_proyecto: { readonly idProyecto: CodecTypes['pg/uuid@1']['output'] };
    readonly in_entidad: {
      readonly codigo_ubigeo: Varchar<6> | null;
      readonly correo_electronico: Varchar<150> | null;
      readonly direccion: Varchar<250> | null;
      readonly es_activo: CodecTypes['pg/bool@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fecha_modificacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id_entidad: CodecTypes['pg/int4@1']['output'];
      readonly nombre_comercial: Varchar<200>;
      readonly razon_social: Varchar<200> | null;
      readonly redes_sociales: Varchar<250> | null;
      readonly ruc: Varchar<11> | null;
      readonly telefono: Varchar<15> | null;
      readonly tipo_entidad: 'PUBLICA' | 'PRIVADA' | 'RELIGIOSA' | 'OTROS';
    };
    readonly in_persona_natural: {
      readonly apellido_materno: Varchar<100> | null;
      readonly apellido_paterno: Varchar<100>;
      readonly codigo_ubigeo: Varchar<6> | null;
      readonly correo_electronico: Varchar<150>;
      readonly direccion: Varchar<250> | null;
      readonly dni: Varchar<8> | null;
      readonly es_activo: CodecTypes['pg/bool@1']['output'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly fecha_modificacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id_persona_natural: CodecTypes['pg/int4@1']['output'];
      readonly nombres: Varchar<100>;
      readonly telefono: Varchar<15> | null;
    };
    readonly in_ubigeo: {
      readonly departamento: Varchar<100>;
      readonly distrito: Varchar<100>;
      readonly id_ubigeo: Varchar<6>;
      readonly provincia: Varchar<100>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly gp_proyecto: { readonly idProyecto: CodecTypes['pg/uuid@1']['input'] };
    readonly in_entidad: {
      readonly codigo_ubigeo: CodecTypes['sql/varchar@1']['input'] | null;
      readonly correo_electronico: CodecTypes['sql/varchar@1']['input'] | null;
      readonly direccion: CodecTypes['sql/varchar@1']['input'] | null;
      readonly es_activo: CodecTypes['pg/bool@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fecha_modificacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id_entidad: CodecTypes['pg/int4@1']['input'];
      readonly nombre_comercial: CodecTypes['sql/varchar@1']['input'];
      readonly razon_social: CodecTypes['sql/varchar@1']['input'] | null;
      readonly redes_sociales: CodecTypes['sql/varchar@1']['input'] | null;
      readonly ruc: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telefono: CodecTypes['sql/varchar@1']['input'] | null;
      readonly tipo_entidad: 'PUBLICA' | 'PRIVADA' | 'RELIGIOSA' | 'OTROS';
    };
    readonly in_persona_natural: {
      readonly apellido_materno: CodecTypes['sql/varchar@1']['input'] | null;
      readonly apellido_paterno: CodecTypes['sql/varchar@1']['input'];
      readonly codigo_ubigeo: CodecTypes['sql/varchar@1']['input'] | null;
      readonly correo_electronico: CodecTypes['sql/varchar@1']['input'];
      readonly direccion: CodecTypes['sql/varchar@1']['input'] | null;
      readonly dni: CodecTypes['sql/varchar@1']['input'] | null;
      readonly es_activo: CodecTypes['pg/bool@1']['input'];
      readonly fecha_creacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly fecha_modificacion: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id_persona_natural: CodecTypes['pg/int4@1']['input'];
      readonly nombres: CodecTypes['sql/varchar@1']['input'];
      readonly telefono: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly in_ubigeo: {
      readonly departamento: CodecTypes['sql/varchar@1']['input'];
      readonly distrito: CodecTypes['sql/varchar@1']['input'];
      readonly id_ubigeo: CodecTypes['sql/varchar@1']['input'];
      readonly provincia: CodecTypes['sql/varchar@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Proyecto = {
    idProyecto: CodecTypes['pg/uuid@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Ubigeo = {
    idUbigeo: Varchar<6>;
    departamento: Varchar<100>;
    provincia: Varchar<100>;
    distrito: Varchar<100>;
    entidades: public_Entidad[];
    personas: public_PersonaNatural[];
    readonly [RelationKeys]?: 'entidades' | 'personas';
  };
  export type public_PersonaNatural = {
    idPersonaNatural: CodecTypes['pg/int4@1']['output'];
    nombres: Varchar<100>;
    apellidoPaterno: Varchar<100>;
    apellidoMaterno: Varchar<100> | null;
    telefono: Varchar<15> | null;
    correoElectronico: Varchar<150>;
    dni: Varchar<8> | null;
    direccion: Varchar<250> | null;
    codigoUbigeo: Varchar<6> | null;
    esActivo: CodecTypes['pg/bool@1']['output'];
    fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    fechaModificacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    ubigeo: public_Ubigeo | null;
    readonly [RelationKeys]?: 'ubigeo';
  };
  export type public_Entidad = {
    idEntidad: CodecTypes['pg/int4@1']['output'];
    ruc: Varchar<11> | null;
    razonSocial: Varchar<200> | null;
    nombreComercial: Varchar<200>;
    tipoEntidad: 'PUBLICA' | 'PRIVADA' | 'RELIGIOSA' | 'OTROS';
    telefono: Varchar<15> | null;
    correoElectronico: Varchar<150> | null;
    redesSociales: Varchar<250> | null;
    direccion: Varchar<250> | null;
    codigoUbigeo: Varchar<6> | null;
    esActivo: CodecTypes['pg/bool@1']['output'];
    fechaCreacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    fechaModificacion: CodecTypes['pg/timestamptz-temporal@1']['output'];
    ubigeo: public_Ubigeo | null;
    readonly [RelationKeys]?: 'ubigeo';
  };
}

export declare const models: {
  public: {
    Proyecto: Models.public_Proyecto;
    Ubigeo: Models.public_Ubigeo;
    PersonaNatural: Models.public_PersonaNatural;
    Entidad: Models.public_Entidad;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly gp_proyecto: {
              columns: {
                readonly idProyecto: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['idProyecto'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly in_entidad: {
              columns: {
                readonly id_entidad: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly ruc: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 11 };
                };
                readonly razon_social: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 200 };
                };
                readonly nombre_comercial: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 200 };
                };
                readonly tipo_entidad: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly telefono: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 15 };
                };
                readonly correo_electronico: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly redes_sociales: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 250 };
                };
                readonly direccion: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 250 };
                };
                readonly codigo_ubigeo: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 6 };
                };
                readonly es_activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly fecha_creacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fecha_modificacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_entidad'] };
              uniques: readonly [{ readonly columns: readonly ['ruc'] }];
              indexes: readonly [
                {
                  readonly name: 'in_entidad_codigo_ubigeo_idx_1bf1466f';
                  readonly prefix: 'in_entidad_codigo_ubigeo_idx';
                  readonly columns: readonly ['codigo_ubigeo'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'in_entidad';
                    readonly columns: readonly ['codigo_ubigeo'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'in_ubigeo';
                    readonly columns: readonly ['id_ubigeo'];
                  };
                },
              ];
            };
            readonly in_persona_natural: {
              columns: {
                readonly id_persona_natural: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nombres: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly apellido_paterno: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly apellido_materno: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly telefono: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 15 };
                };
                readonly correo_electronico: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly dni: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 8 };
                };
                readonly direccion: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 250 };
                };
                readonly codigo_ubigeo: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 6 };
                };
                readonly es_activo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly fecha_creacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly fecha_modificacion: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_persona_natural'] };
              uniques: readonly [{ readonly columns: readonly ['dni'] }];
              indexes: readonly [
                {
                  readonly name: 'in_persona_natural_codigo_ubigeo_idx';
                  readonly columns: readonly ['codigo_ubigeo'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'in_persona_natural';
                    readonly columns: readonly ['codigo_ubigeo'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'in_ubigeo';
                    readonly columns: readonly ['id_ubigeo'];
                  };
                },
              ];
            };
            readonly in_ubigeo: {
              columns: {
                readonly id_ubigeo: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 6 };
                };
                readonly departamento: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly provincia: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly distrito: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
              };
              primaryKey: { readonly columns: readonly ['id_ubigeo'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly in_tipo_entidad: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PUBLICA', 'PRIVADA', 'RELIGIOSA', 'OTROS'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly gp_proyecto: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Proyecto';
    };
    readonly in_ubigeo: { readonly namespace: 'public' & NamespaceId; readonly model: 'Ubigeo' };
    readonly in_persona_natural: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PersonaNatural';
    };
    readonly in_entidad: { readonly namespace: 'public' & NamespaceId; readonly model: 'Entidad' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Entidad: {
            readonly fields: {
              readonly idEntidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ruc: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 11 };
                };
              };
              readonly razonSocial: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 200 };
                };
              };
              readonly nombreComercial: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 200 };
                };
              };
              readonly tipoEntidad: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefono: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 15 };
                };
              };
              readonly correoElectronico: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly redesSociales: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 250 };
                };
              };
              readonly direccion: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 250 };
                };
              };
              readonly codigoUbigeo: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 6 };
                };
              };
              readonly esActivo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly fechaCreacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fechaModificacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly ubigeo: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ubigeo';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['codigoUbigeo'];
                  readonly targetFields: readonly ['idUbigeo'];
                };
              };
            };
            readonly storage: {
              readonly table: 'in_entidad';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idEntidad: { readonly column: 'id_entidad' };
                readonly ruc: { readonly column: 'ruc' };
                readonly razonSocial: { readonly column: 'razon_social' };
                readonly nombreComercial: { readonly column: 'nombre_comercial' };
                readonly tipoEntidad: { readonly column: 'tipo_entidad' };
                readonly telefono: { readonly column: 'telefono' };
                readonly correoElectronico: { readonly column: 'correo_electronico' };
                readonly redesSociales: { readonly column: 'redes_sociales' };
                readonly direccion: { readonly column: 'direccion' };
                readonly codigoUbigeo: { readonly column: 'codigo_ubigeo' };
                readonly esActivo: { readonly column: 'es_activo' };
                readonly fechaCreacion: { readonly column: 'fecha_creacion' };
                readonly fechaModificacion: { readonly column: 'fecha_modificacion' };
              };
            };
          };
          readonly PersonaNatural: {
            readonly fields: {
              readonly idPersonaNatural: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nombres: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly apellidoPaterno: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly apellidoMaterno: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly telefono: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 15 };
                };
              };
              readonly correoElectronico: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly dni: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 8 };
                };
              };
              readonly direccion: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 250 };
                };
              };
              readonly codigoUbigeo: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 6 };
                };
              };
              readonly esActivo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly fechaCreacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fechaModificacion: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly ubigeo: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Ubigeo';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['codigoUbigeo'];
                  readonly targetFields: readonly ['idUbigeo'];
                };
              };
            };
            readonly storage: {
              readonly table: 'in_persona_natural';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idPersonaNatural: { readonly column: 'id_persona_natural' };
                readonly nombres: { readonly column: 'nombres' };
                readonly apellidoPaterno: { readonly column: 'apellido_paterno' };
                readonly apellidoMaterno: { readonly column: 'apellido_materno' };
                readonly telefono: { readonly column: 'telefono' };
                readonly correoElectronico: { readonly column: 'correo_electronico' };
                readonly dni: { readonly column: 'dni' };
                readonly direccion: { readonly column: 'direccion' };
                readonly codigoUbigeo: { readonly column: 'codigo_ubigeo' };
                readonly esActivo: { readonly column: 'es_activo' };
                readonly fechaCreacion: { readonly column: 'fecha_creacion' };
                readonly fechaModificacion: { readonly column: 'fecha_modificacion' };
              };
            };
          };
          readonly Proyecto: {
            readonly fields: {
              readonly idProyecto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'gp_proyecto';
              readonly namespaceId: 'public';
              readonly fields: { readonly idProyecto: { readonly column: 'idProyecto' } };
            };
          };
          readonly Ubigeo: {
            readonly fields: {
              readonly idUbigeo: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 6 };
                };
              };
              readonly departamento: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly provincia: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly distrito: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
            };
            readonly relations: {
              readonly entidades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Entidad';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idUbigeo'];
                  readonly targetFields: readonly ['codigoUbigeo'];
                };
              };
              readonly personas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PersonaNatural';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idUbigeo'];
                  readonly targetFields: readonly ['codigoUbigeo'];
                };
              };
            };
            readonly storage: {
              readonly table: 'in_ubigeo';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idUbigeo: { readonly column: 'id_ubigeo' };
                readonly departamento: { readonly column: 'departamento' };
                readonly provincia: { readonly column: 'provincia' };
                readonly distrito: { readonly column: 'distrito' };
              };
            };
          };
        };
        readonly enum: {
          readonly in_tipo_entidad: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PUBLICA'; readonly value: 'PUBLICA' },
              { readonly name: 'PRIVADA'; readonly value: 'PRIVADA' },
              { readonly name: 'RELIGIOSA'; readonly value: 'RELIGIOSA' },
              { readonly name: 'OTROS'; readonly value: 'OTROS' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'gp_proyecto';
            readonly column: 'idProyecto';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'in_entidad';
            readonly column: 'fecha_modificacion';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'in_persona_natural';
            readonly column: 'fecha_modificacion';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
